### PR TITLE
FormData : add polyfill

### PR DESCRIPTION
**Pull request by romainmenke**
fixes : https://github.com/Financial-Times/polyfill-library/issues/31

Any feedback is welcome!

- I am pretty sure that the list of dependencies is incomplete.
- What is the policy around tests for external polyfills? The lib seems to have extensive tests, should tests be written here too?

### CODE REVIEW

**Comment by JakeChampion** [comment]
Thanks for the pull request. Yes, we want to have some tests for this inside polyfill library to show it works on all the browsers we support  would you be able to add some to this pull request?

**Comment by romainmenke** [comment]
@JakeChampion Tests were added.

- added some "naive" tests that test basic behaviour.
- also used the tests for `Map` as a basis for more extensive testing.

These all pass in latest Chrome but fail in older browsers like IE10.

It seems some fixes have to be done upstream first before this can be merged.

**Comment by romainmenke** [comment]
@JakeChampion I have been going through the FormData polyfill and it's tests and there some parts I feel are very flaky.

Things that worry me :

- [global.File override](https://github.com/jimmywarting/FormData/blob/master/FormData.js#L39-L71)
- [more patches](https://github.com/jimmywarting/FormData/blob/master/FormData.js#L413-L453)
- [tests include more logic and overrides](https://github.com/jimmywarting/FormData/blob/master/test/test.js#L3-L21)

This polyfill probably works great on it's own, but as it stands now it is impossible to judge how it will interact with other packages in `polyfill-library`.

Do you think it best to fix upstream or look for a different solution?

**Comment by isocroft** [comment]
Hello, i just erroneosly created another PR for the inclusion of this [**FormData** feature](https://github.com/Financial-Times/polyfill-library/pull/677). Can we work on this so we can get it cleared and merged as soon as possible.

**Comment by romainmenke** [comment]
@isocroft At the moment I don't think the FormData polyfill is suitable to include here.
I am working on a fork the get familiarised with it more first.
From there I will probably send some tweaks upstream.

At the moment I am mostly looking at the test suite and some interop issues between the polyfill and native implementations.
After that I will still need to check for compatiblity issues between the polyfill and things like `fetch` and `blob`.

If someone is willing to help out I will gladly make a list of separate issues I see.

**Comment by isocroft** [comment]
Alright, I am wiling to help @romainmenke . Please, loop me in as soon as you make the list. Thanks

**Comment by romainmenke** [comment]
@JakeChampion yes, still working on it.

Only had limited time the past few weeks, hoping my schedule will clear up a bit.

First issue I am trying to tackle is to provide polyfills for all dependencies of FormData.
For example File needs a polyfill and this should not be provided by the FormData polyfill.

Finished a good first draft of the File polyfill yesterday and hoping to write tests for it during this week.

**Comment by JakeChampion** [comment]
@romainmenke that sounds exciting :-D Thank you for working on this!

**Comment by isocroft** [comment]
@JakeChampion thanks for linking my PR here. @romainmenke could you spare a little time next weekend so we can put heads together on how to finish up this PR ? 

1. We can move [this](https://github.com/jimmywarting/FormData/blob/master/FormData.js#L39-L71) into it's own `polyfills/File/polyfill.js` file using the `polyfills/File/detect.js` file for **global.File** constructor.

2. We can also move [these monkey patches](https://github.com/jimmywarting/FormData/blob/master/FormData.js#L413-L453) into [here](https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/XMLHttpRequest/polyfill.js#L63-L69) for **global.XMLHttpRequest** method(s) into the `polyfills/XMLHttpRequest/polyfill.js` file.

3. [This](https://github.com/jimmywarting/FormData/blob/master/FormData.js#L342-L368) piece of logic needs to move into the `polyfills/XMLHttpRequest/polyfill.js` file. specifically for `global.XMLHttpRequest.prototype.send()`

**Comment by isocroft** [comment]
@JakeChampion thanks for linking my PR here. @romainmenke could you spare a little time next weekend so we can put heads together on how to finish up this PR ?

We can move this into it's own polyfills/File/polyfill.js file using the polyfills/File/detect.js file for global.File constructor. This File logic can also be merged with this.

We can also move these monkey patches into here for global.XMLHttpRequest method(s) into the polyfills/XMLHttpRequest/polyfill.js file.

This piece of logic needs to move into the polyfills/XMLHttpRequest/polyfill.js file. specifically for global.XMLHttpRequest.prototype.send() to handle FormData submission using either native Blob() or the eligrey's polyfill for Blob().

```js

function blobToBase64(blob, contentType) {

}

function base64ToArrayBuffer(base64, contentType) {
        contentType = contentType || base64.match(/^data\:([^\;]+)\;base64,/mi)[1] || ''; 
        base64 = base64.replace(/^data\:([^\;]+)\;base64,/gmi, '');

        var binary = atob(base64);
        var len = binary.length;
        var buffer = new ArrayBuffer(len);
        var view = new Uint8Array(buffer);

        for (var i = 0; i < len; i++) {
            view[i] = binary.charCodeAt(i);
        }

        return buffer;
}


function bufferToString = (arrayBuffer) {
    return String.fromCharCode(...new Uint8Array(arrayBuffer));
};

function as_binary(blob) {
    return bufferToString(
                base64ToArrayBuffer(
                        blobToBase64(blob, blob.type)
               , blob.type)
    );
}

function is_binary(type){
   return /^(?:image/(?:png|jpe?g|gif))|(?:application/(?:pdf|octet-stream))$/
};

 var str_multipart = function(boundary, formValues){
        var CRLF = "/r/n";
        var bits = ["--".concat(boundary, CRLF)];
     
        for(var name in formValues){
             if (formValues.hasOwnProperty(name)) {
                   var value = formValues[name];
                  
                   bits.push(value instanceof Blob ? "".concat(
                        'Content-Disposition: form-data; name="', name, '"; filename="', (value.fileName || value.name), '"', CRLF,
                        'Content-Type: ', (value.type || 'application/octet-stream'), CRLF,
                        CRLF, (is_binary(value.type || 'application/octet-stream') ? (!!value.getAsBinary &&  value.getAsBinary()) || 
                        as_binary(value) : (!!value.getAsText && value.getAsText() || as_binary(value)), CRLF) : "".concat(
                        'Content-Disposition: form-data; name="', name, '"', CRLF, CRLF, value, CRLF);
              }
        }

        bits.push("--".concat(boundary, "--", CRLF));
        
        return bits;
  };

global.XMLHttpRequest.prototype.setRequestHeader = function (name, value) {
      _setRequestHeader.call(this, name, value)
      if (name.toLowerCase() === 'content-type') this._hasContentType = true
};

global.XMLHttpRequest.prototype.send = function (data) {
       if(typeof data !== 'undefined' && data !== null){
               var contentType;
               var chunk;

              if (typeof data.append === 'function') {
                  var boundary = "AjaxBoundary" + (new Date).getTime();
                  contentType = 'multipart/form-data; boundary=' + boundary;
                   
                  chunk = data._formdataPolyfill === true ? str_mutipart(boundary, data) : data;
              } else if(data instanceof Blob) {
                  contentType = data.type;
                
                  chunk = [data];
              }
            
             // need to patch send b/c old IE don't send blob's type (#44)
             if (!this._hasContentType && contentType) {
                 this.setRequestHeader('Content-Type', contentType);
             }
             
             this._hasContentType = false;

             typeof this.sendAsBinary !== 'undefined' 
               ? this.sendAsBinary.call(this,  new Blob(chunk, { type: contentType })) 
                : _send.call(this, typeof chunk.join === 'function' ? chunk.join('') : chunk);
           }
         }
         
         _send.call(this, data)
    }

**Comment by JakeChampion** [comment]
Why the repost @isocroft ?

**Comment by isocroft** [comment]
I am trying to think through how to synchronously convert a blob to a base64 string. In the meantime i wanted to keep the uncompleted code.

**Comment by romainmenke** [comment]
Hey @isocroft

Have personally been swamped at work. As things look right now my schedule will clear up from October.

Aside from that I also think we should wait with this polyfill until the `Intl` update fully settles.
Otherwise we risk blocking releases too much.

**Comment by romainmenke** [comment]
@isocroft see : https://github.com/Financial-Times/polyfill-library/pull/715#issuecomment-709979113

Aside from the issues flagged there I have limited capacity to contribute here and would prefer to focus on general healthiness of the project.

If you want, you can take over, otherwise I suggest we close this as there is a working [alternative](https://github.com/jimmywarting/FormData).

**Comment by JakeChampion** [comment]
@romainmenke Let's close this PR, another one can get created if someone wants to give it another go 👍

**Pull request closed without merging**
