### PR TITLE
Adds `Node.prototype.isSameNode` polyfill

### PR DESCRIPTION
**Pull request by mhassan1**
Resolves https://github.com/Financial-Times/polyfill-library/issues/300

### CODE REVIEW

**Comment by JakeChampion** [comment]
Thanks @mhassan1 - this is now running on CI over at https://github.com/Financial-Times/polyfill-library/actions/runs/1545824484

**Comment by romainmenke** [comment]
I started on this a while back and eventually abandoned it because I lacked time.
In my version I added a bunch more cases for other types.

https://github.com/romainmenke/polyfill-library/blob/522b4a391792732c7347c711d9ef514d885125b7/polyfills/Node/prototype/isSameNode/polyfill.js

Maybe this isn't needed in which case you can ignore this comment :)
It's too long ago for me to know exactly if these were important and if there were more issues to be resolved.

**Comment by JakeChampion** [comment]
> I started on this a while back and eventually abandoned it because I lacked time. In my version I added a bunch more cases for other types.
> 
> [romainmenke/polyfill-library@`522b4a3`/polyfills/Node/prototype/isSameNode/polyfill.js](https://github.com/romainmenke/polyfill-library/blob/522b4a391792732c7347c711d9ef514d885125b7/polyfills/Node/prototype/isSameNode/polyfill.js)
> 
> Maybe this isn't needed in which case you can ignore this comment :) It's too long ago for me to know exactly if these were important and if there were more issues to be resolved.

It looks like the polyfill you were writing was aiming to work for Internet Explorer 8, which this polyfill currently is not aiming to do.

It would be good to bring in those tests though as they are quite comprehensive 👍

**Comment by romainmenke** [comment]
Maybe easiest if I open a separate PR later to add the extra tests?

**Comment by JakeChampion** [comment]
> Maybe easiest if I open a separate PR later to add the extra tests?

that is good with me ☺️

**Review by JakeChampion — APPROVED** [review]

**Comment by romainmenke** [comment]
@JakeChampion Wanted to add the tests and it's starting to come back to me why this was more work than I expected :)

The full WPT test suite is not achievable as not all node types can be patched.
When comparing text nodes for example you get `Invalid pointer` errors.
Going to leave this as is :)

Thank you @mhassan1 for this polyfill!

**Pull request merged**
