### PR TITLE
When testing, include all polyfills which target the browser rather than only the polyfill being tested

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by romainmenke** [comment]
@JakeChampion Most of the smaller issues have been resolved.
There is still a failure in `Object.create` [details here](https://github.com/Financial-Times/polyfill-library/pull/926)
If I remove the polyfill for `Symbol.prototype.description` (thereby fixing Symbol) all tests pass except the issue with `Object.create`.

Would be great to get that last one resolved and those PR's merged before tackling the issues with `Symbol`.

**Comment by romainmenke** [comment]
ugh, jinxed it 🙂 

`Blob` introduces the same issue as `Symbol.prototype.description`. It wraps `URL` which breaks the polyfill.

**Comment by romainmenke** [comment]
@JakeChampion we could also merge individual fixes into master first.
Now CI always fails on IE because of other issues, making it harder to be sure that a fix doesn't introduce new bugs in for example Chrome.

**Comment by JakeChampion** [comment]
> @JakeChampion we could also merge individual fixes into master first.
> Now CI always fails on IE because of other issues, making it harder to be sure that a fix doesn't introduce new bugs in for example Chrome.

Happy to have PRs raised against master also :-)

**Comment by romainmenke** [comment]
I though we had many more fixes to go but my reference branch just passed CI.
https://github.com/romainmenke/polyfill-library/runs/1512380286?check_suite_focus=true

This has one test skip for `Object.create` and `Polyfill.prototype.description` was removed.

**Comment by JakeChampion** [comment]
> I though we had many more fixes to go but my reference branch just passed CI.
> [romainmenke/polyfill-library/runs/1512380286?check_suite_focus=true](https://github.com/romainmenke/polyfill-library/runs/1512380286?check_suite_focus=true)
> 
> This has one test skip for `Object.create` and `Polyfill.prototype.description` was removed.

I don't know how to make object.create work for ie8 correctly :/, maybe we need to skip it for now

**Comment by romainmenke** [comment]
I think all needed fixes and changes are done now.
Any branch that you are ok with can be merged.

I am available to address feedback each day early evening (or during the weekend).
There is no prio to ship all these changes on my end, so we can take our time with this 🙂

**Comment by JakeChampion** [comment]
> I think all needed fixes and changes are done now.
> Any branch that you are ok with can be merged.
> 
> I am available to address feedback each day early evening (or during the weekend).
> There is no prio to ship all these changes on my end, so we can take our time with this 🙂

I'm now running a test on CI with all the branches merged into one -- https://github.com/Financial-Times/polyfill-library/runs/1518927776

Thank you so much for this tremendous amount of work @romainmenke!

**Comment by romainmenke** [comment]
https://github.com/Financial-Times/polyfill-library/compare/polyfill-fixes#diff-8b5e449fd0e810ce110e9c5206f5ca293a88e745c18eed040f96e4ae986e0c99R194

`var source = create(null);` -> `var source = objectCreate(null);`

I had the same merge conflict :)

**Comment by JakeChampion** [comment]
> [`polyfill-fixes`#diff-8b5e449fd0e810ce110e9c5206f5ca293a88e745c18eed040f96e4ae986e0c99R194 (compare)](https://github.com/Financial-Times/polyfill-library/compare/polyfill-fixes#diff-8b5e449fd0e810ce110e9c5206f5ca293a88e745c18eed040f96e4ae986e0c99R194)
> 
> `var source = create(null);` -> `var source = objectCreate(null);`
> 
> I had the same merge conflict :)
> 
> And you're welcome!

Thanks for spotting that, here is the new build -- https://github.com/Financial-Times/polyfill-library/runs/1518981226

**Comment by romainmenke** [comment]
https://github.com/Financial-Times/polyfill-library/runs/1520975313

Was there a screen capture in browser stack for the iOS12 run?

`Browser: ios/12 Test config: targeted / combined / shard n/a ✘ 340 tests, 3 failures  17 seconds to complete`

Took a diff between my branch which passed and yours and it was clean. Maybe a flaky run?

**Comment by JakeChampion** [comment]
> https://github.com/Financial-Times/polyfill-library/runs/1520975313
> 
> Was there a screen capture in browser stack for the iOS12 run?
> 
> `Browser: ios/12 Test config: targeted / combined / shard n/a ✘ 340 tests, 3 failures 17 seconds to complete`
> 
> Took a diff between my branch which passed and yours and it was clean. Maybe a flaky run?

That was a flaky run, yes :-)

I'm rerunning the last commit on this branch right now 👍 -- https://github.com/Financial-Times/polyfill-library/pull/924/checks?check_run_id=1527634947

**Comment by JakeChampion** [comment]
Excellent worrk here @romainmenke 🙌

**Comment by romainmenke** [comment]
Awesome!

Thank you for all the time and effort that went into reviewing and validating these changes!

**Comment by romainmenke** [comment]
@JakeChampion Can you create a release for these changes? 🙇

**Comment by JakeChampion** [comment]
> @JakeChampion Can you create a release for these changes? 🙇

Done 👍 -- https://github.com/Financial-Times/polyfill-library/releases/tag/v3.99.0

**Pull request merged**
