### PR TITLE
fix arraybuffer polyfill to not error in ie8

### PR DESCRIPTION
**Pull request by JakeChampion**
Fixes https://github.com/Financial-Times/polyfill-library/issues/1129

### CODE REVIEW

**Review by notlee — APPROVED** [review]

**Comment by romainmenke** [comment]
Thank you @JakeChampion!

Started a run with the polyfill combinations : https://github.com/romainmenke/polyfill-library/runs/4447515393?check_suite_focus=true

**Comment by romainmenke** [comment]
Seeing one failure in IE8 for TextDecoder when all polyfills are loaded.

Screenshot 2021-12-07 at 18 57 01

**Comment by JakeChampion** [comment]
Doing a git bisect it looks like the issue was exposed in this commit https://github.com/Financial-Times/polyfill-library/commit/29c6814f885bc80a0f289c6932bd6340d7f00951 - I haven't found the cause yet but I'm getting closer

**Comment by JakeChampion** [comment]
@romainmenke This should now be fixed 👍

**Comment by JakeChampion** [comment]
A full run is takiing place on https://github.com/Financial-Times/polyfill-library/actions/runs/1554495111

**Pull request merged**
