### PR TITLE
switch the global object from being `this` to being an argument named `self`

### PR DESCRIPTION
**Pull request by JakeChampion**
This enables the bundle to work in strict mode, which some of our users are trying to execute the bundle in.

Solves #297 
Solves #298
Solves #314

This work should hopefully enable us to merge in #226

### CODE REVIEW

**Comment by notlee** [comment]
🤞 you can do it browserstack!

**Comment by niksy** [comment]
When can we expect this to be merged? Anything we can help with?

**Comment by notlee** [comment]
👍 This time!? I still approve; I approve more than ever

**Comment by jimmywarting** [comment]
hmm, maybe a bit late to the party but shouldn't it have been [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) instead?

**Comment by JakeChampion** [comment]
@jimmywarting It will be eventually, yes :-)

**Pull request merged**
