### PR TITLE
Intl dependency config update

### PR DESCRIPTION
**Pull request by romainmenke**
### Intl dependency config update :

If someone intends to use `DateTimeFormat` with locale `af-NA` they will also require `NumberFormat` and `Intl.NumberFormat.~locale.af-NA`.

This change adds those locale dependencies to `Intl` polyfills.

locale : `af-NA`

`polyfills/Intl/DateTimeFormat/~locale/af-NA/config.toml`

```diff
 dependencies = [
   "Array.isArray",
   "Array.prototype.filter",
   "Array.prototype.indexOf",
   "Array.prototype.lastIndexOf",
   "Array.prototype.map",
   "Array.prototype.reduce",
   "Date.now",
   "Intl.DateTimeFormat",
   "Intl.Locale",
   "Intl.NumberFormat",
+  "Intl.NumberFormat.~locale.af-NA",
   "Intl.getCanonicalLocales",
   "Object.assign",
   "Object.create",
   "Object.keys",
   "Object.setPrototypeOf",
   "Set",
   "WeakMap"
 ]
```

---------------

`PluralRules` has no `region` specific data so the locale is split and the first part is used for a lookup :

locale : `ar-BH`

`polyfills/Intl/NumberFormat/~locale/ar-BH/config.toml`

```diff
 dependencies = [
   "Array.isArray",
   "Array.prototype.filter",
   "Array.prototype.forEach",
   "Array.prototype.indexOf",
   "Array.prototype.lastIndexOf",
   "Array.prototype.map",
   "Array.prototype.reduce",
   "Intl.Locale",
   "Intl.NumberFormat",
   "Intl.PluralRules",
+  "Intl.PluralRules.~locale.ar",
   "Intl.getCanonicalLocales",
   "Object.assign",
   "Object.create",
   "Object.defineProperty",
   "Object.keys",
   "Object.setPrototypeOf",
   "WeakMap"
 ]
```

@longlho I hope this is correct. If this is not actually how the polyfills should be used/configured then I don't mind removing this change.

### CODE REVIEW

**Comment by longlho** [comment]
I think this PR conflates 2 things, 1 is polyfill dep & the other is `DateTimeFormat` tz. I'd prefer splitting them out because the format actually requires the full polyfill dep tree so `DateTimeFormat-ar` -> `NumberFormat-ar` -> `PluralRules-ar`. There're also locale negotiation going on because not all polyfills have the same set of supported locales.

The later (adding tz support) is much easier though.

**Comment by romainmenke** [comment]
@longlho Thank you for the fast feedback.
This change has been split up. With this PR focussed on the config change.

--------------

> the format actually requires the full polyfill dep tree so DateTimeFormat-ar -> NumberFormat-ar -> PluralRules-ar.

That is correct and this should be covered.

`Intl.DateTimeFormat.~locale.ar` has these direct dependencies : 

```
  "Intl.DateTimeFormat",
  "Intl.Locale",
  "Intl.NumberFormat",
  "Intl.NumberFormat.~locale.ar",
  "Intl.getCanonicalLocales",
```

`Intl.NumberFormat.~locale.ar` has it's own set of dependencies :

```
  "Intl.Locale",
  "Intl.NumberFormat",
  "Intl.PluralRules",
  "Intl.PluralRules.~locale.ar",
  "Intl.getCanonicalLocales",
```

`Intl.PluralRules.~locale.ar` :

```
  "Intl.getCanonicalLocales",
  "Intl.Locale",
```

Combined and deduplicated : 

```
  "Intl.DateTimeFormat",
  "Intl.Locale",
  "Intl.NumberFormat",
  "Intl.NumberFormat.~locale.ar",
  "Intl.PluralRules",
  "Intl.PluralRules.~locale.ar",
  "Intl.getCanonicalLocales",
```

I did notice that `RelativeTimeFormat` declares both `NumberFormat` and `PluralRules` even though `DateTimeFormat` only lists `NumberFormat` as a direct dependency. I followed the logic/config that was already in place, but maybe one of these is better?

---------

> There're also locale negotiation going on because not all polyfills have the same set of supported locales.

This is the bit I am must unsure about. ~~I was hoping that there is a straight forward mapping of `NumberFormat` locales to `PluralRules` locales. But my implementation might be naive.~~

I have updated to update tasks to use this logic : https://github.com/formatjs/formatjs/blob/main/packages/ecma402-abstract/BestAvailableLocale.ts

`pluralRulesLocales` : `Set` with existing `PluralRules` locales.

| polyfill locale | `PluralRules` locale |
| --- | --- |
| `ar` | `ar` |
| `ar-AE` | `ar` |
| `az-Cyrl` | `az` |
| `ca-ES-VALENCIA` | `ca` |
| `en-US-POSIX` | `en` |
| `pt-PT` | `pt-PT` |

**Comment by longlho** [comment]
can you switch to use https://www.npmjs.com/package/@formatjs/intl-localematcher instead? `@formatjs/ecma402-abstract` is meant to be private

**Review by longlho — APPROVED** [review]

**Review by JakeChampion — APPROVED** [review]
Thank you so much for this @romainmenke and @longlho

**Pull request merged**
