### PR TITLE
chore: upgrade formatjs libs + add Intl.Locale polyfill

### PR DESCRIPTION
**Pull request by longlho**
- New `@formatjs/intl-datetimeformat` has support for stage 3 `formatRange`
- Add Intl.Locale polyfill
- Bug fixes
- Improve `best fit` locale negotiation
- Upgrade `tzdata` to version 2020d

### CODE REVIEW

**Comment by JakeChampion** [comment]
Thanks for updating Intl once again @longlho :-)
Testing on CI for this finished and has some test failures which are:
```
Failures:
 - ie/10.0:
    -> Intl.DateTimeFormat passes the feature detect
       Missing locale data for undefined
 - ie/10.0:
    -> Intl.DateTimeFormat formatToParts should work
       Missing locale data for undefined
 - ie/10.0:
    -> Intl.DateTimeFormat should fix dayperiod bug in chrome
       Missing locale data for undefined
 - ie/11.0:
    -> Intl.DateTimeFormat passes the feature detect
       Missing locale data for undefined
 - ie/11.0:
    -> Intl.DateTimeFormat formatToParts should work
       Missing locale data for undefined
 - ie/11.0:
    -> Intl.DateTimeFormat should fix dayperiod bug in chrome
       Missing locale data for undefined
 - ie/9.0:
    -> Intl.DateTimeFormat passes the feature detect
       Missing locale data for undefined
 - ie/9.0:
    -> Intl.DateTimeFormat formatToParts should work
       Missing locale data for undefined
 - ie/9.0:
    -> Intl.DateTimeFormat should fix dayperiod bug in chrome
       Missing locale data for undefined
```

If you run `npm run watch`, you can then visit `http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.DateTimeFormat` in a browser to run the tests.

**Comment by longlho** [comment]
ok it's the CLDR updated data again. I've updated the tests.

**Comment by romainmenke** [comment]
@longlho Seems like you have a JS linter in your code editor that also applied a lot of changes (lot's of trailing comma's added). These cause a lint error. Can you maybe add some info on your editor setup? If I can replicate I might be able to avoid it with a config file as that would also help other contributors 🙂 

@JakeChampion thoughts on this?

**Comment by longlho** [comment]
Yeah something like .editorconfig would be nice or prettier

**Comment by romainmenke** [comment]
Eslint is used and configured so I think we just need to make sure editors pick it up and do not run other linters.

**Comment by longlho** [comment]
Hmm I don't see the lint err in the build. Does it not run in CI?

**Comment by romainmenke** [comment]
I ran CI on my fork after noticing the added changes : https://github.com/romainmenke/polyfill-library/runs/1407591978?check_suite_focus=true

**Comment by JakeChampion** [comment]
Apologies for the delay on this @longlho, I've been on holiday for 2 weeks and have stayed away from GitHub mostly.

I ran on our CI and it looks like IE 9 and IE 10 are failing the tests:
```
Failures:
 - ie/9.0 and ie/10.0:
    -> Intl.DateTimeFormat passes the feature detect
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.DateTimeFormat
       false == true
    -> Intl.DateTimeFormat formatToParts should work
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.DateTimeFormat
       Object doesn't support this action
    -> Intl.DateTimeFormat should fix dayperiod bug in chrome
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.DateTimeFormat
       Object doesn't support this action
 - ie/9.0 and ie/10.0:
    -> Intl.DisplayNames passes the feature detect
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.DisplayNames
       false == true
    -> Intl.DisplayNames Intl.DisplayNames should be able to resolve Latin America
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.DisplayNames
       Object doesn't support this action
 - ie/9.0 and ie/10.0:
    -> Intl.ListFormat passes the feature detect
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.ListFormat
       false == true
    -> Intl.ListFormat Intl.ListFormat format should work for style conjunction
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.ListFormat
       Object doesn't support this action
 - ie/9.0 and ie/10.0:
    -> Intl.NumberFormat passes the feature detect
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.NumberFormat
       false == true
    -> Intl.NumberFormat format should work for compact notation
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.NumberFormat
       Object doesn't support this action
 - ie/9.0 and ie/10.0:
    -> Intl.PluralRules passes the feature detect
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.PluralRules
       false == true
    -> Intl.PluralRules Intl.PluralRules should work for cardinal
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.PluralRules
       Object doesn't support this action
    -> Intl.PluralRules Intl.PluralRules should work for ordinal
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.PluralRules
       Object doesn't support this action
 - ie/9.0 and ie/10.0:
    -> Intl.RelativeTimeFormat passes the feature detect
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.RelativeTimeFormat
       false == true
    -> Intl.RelativeTimeFormat Intl.RelativeTimeFormat format should work for style narrow
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.RelativeTimeFormat
       Object doesn't support this action
    -> Intl.RelativeTimeFormat Intl.RelativeTimeFormat format should work for numeric auto
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.RelativeTimeFormat
       Unable to get property 'prototype' of undefined or null reference
    -> Intl.RelativeTimeFormat Intl.RelativeTimeFormat formatToParts should work for numeric auto
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.RelativeTimeFormat
       Unable to get property 'prototype' of undefined or null reference
```

**Comment by longlho** [comment]
another try :) ?

**Comment by JakeChampion** [comment]
@longlho it now seems to consistently crash in certain IE versions.
```
 • Browser: ie/10.0 Testing mode: targeted ✘ 1365 tests, 1 failures  142 seconds to complete
 • Browser: ie/11.0 Testing mode: targeted ✘ 1385 tests, 1 failures  147 seconds to complete
 • Browser: ie/8.0 Testing mode: targeted ✓ 1449 tests  49 seconds to complete
 • Browser: ie/9.0 Testing mode: targeted ✘ 1429 tests, 1 failures  143 seconds to complete
```

**Comment by longlho** [comment]
Hmm no stack trace?

**Comment by JakeChampion** [comment]
> Hmm no stack trace?

Not in the logs, looks like we need to do a manual test in those browsers and see what the issue is

**Comment by longlho** [comment]
hmm I can't repro it locally :(

**Review by JakeChampion — APPROVED** [review]

**Pull request merged**
