### PR TITLE
Adding the inert polyfill

### PR DESCRIPTION
**Pull request by andrewgadziksonos**
👋 Hello, first time contributor here.  

Looking to add the inert polyfill here with the understanding that its not supported in any browser at the moment (but hopefully in the future).  This feels like a good place for this to live as you can control the inertness of an element through `Element.prototype.inert` and seems to follow the other `Element.prototype` polyfill conventions.  

Happy to discuss any feedback 👂

### CODE REVIEW

**Comment by JakeChampion** [comment]
Hey @andrewgadziksonos, this is a great pull-request, thank you for taking the time to do this.

May I ask how the experience was for learning how to contribute? If we can improve the experience in any way, I'd love for us to do that.

It looks like [Chrome 76 will have an implementation](https://wpt.fyi/results/inert?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned&q=inert), perhaps we should not target Chrome versions 76 or higher?

**Comment by andrewgadziksonos** [comment]
> May I ask how the experience was for learning how to contribute? If we can improve the experience in any way, I'd love for us to do that.

The contribution documentation was great.  The only weird thing to me was that there was no _HowTo-Add New Polyfill_ section in that documentation.  I had to look at the existing polyfills as my examples.  Pretty straight forward though, I love how easy it was.

> It looks like [Chrome 76 will have an implementation](https://wpt.fyi/results/inert?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned&q=inert), perhaps we should not target Chrome versions 76 or higher?

Nice find, I'll make the fix

**Comment by andrewgadziksonos** [comment]
@JakeChampion is there anything you need from me on my end?  Happy to help out with anything that you need.

**Comment by JakeChampion** [comment]
@andrewgadziksonos I've optimised our CI setup for third-party-polyfills, it should be much faster to run the full test suite now and hopefully we can push this pull-request into master soon!

**Comment by JakeChampion** [comment]
This currently won't work in ES3 environments due to the polyfill using keywords as method names in dot-notation. I've submitted a pull-request which converts the dot-notation to bracket-notation to make it work in ES3 environments, once that is merged we can hopefully finish off this pull-request.

https://github.com/WICG/inert/pull/125

**Comment by andrewgadziksonos** [comment]
> This currently won't work in ES3 environments due to the polyfill using keywords as method names in dot-notation. I've submitted a pull-request which converts the dot-notation to bracket-notation to make it work in ES3 environments, once that is merged we can hopefully finish off this pull-request.
> 
> [WICG/inert#125](https://github.com/WICG/inert/pull/125)

Sounds good - thank you for the update!

**Pull request merged**
