### PR TITLE
Adds update task to `ArrayBuffer` to fix incomplete browser implementations

### PR DESCRIPTION
**Pull request by mhassan1**
This PR partially fixes https://github.com/Financial-Times/polyfill-library/issues/1132 using an update task on the `ArrayBuffer` polyfill:
* replaces `global.ArrayBuffer = global.ArrayBuffer || ArrayBuffer` with `global.ArrayBuffer = ArrayBuffer` (and friends) so that the polyfill implementation replaces incomplete browser implementations (e.g. IE11)
* replaces `Object.defineProperty` usage with a wrapper function that sets `configurable: true` and `writable: true`, which matches modern browser implementations

It also adds basic tests of the `ArrayBuffer` polyfill.

### CODE REVIEW

**Comment by mhassan1** [comment]
@chee @JakeChampion Is anything blocking this PR?

**Comment by JakeChampion** [comment]
Tests are running at https://github.com/Financial-Times/polyfill-library/actions/runs/2589960662

**Comment by mhassan1** [comment]
@JakeChampion Thanks. I've made a couple small fixes for IE. Other two failures seem like flaky tests that may complete on the next run. Please re-run.

**Pull request merged**
