### PR TITLE
chore: upgrade formatjs polyfills

### PR DESCRIPTION
**Pull request by longlho**
Depends on #642

### CODE REVIEW

**Comment by longlho** [comment]
Aight I think I've fixed the issues

**Comment by JakeChampion** [comment]
It looks like the test locale data for `Intl.RelativeTimeFormat` in not in the expected format.

https://github.com/Financial-Times/polyfill-library/pull/665/files#diff-a22dbd486f5a3da1c3086cc8e2b681c6R20

```
Failures:
- chrome/29.0 up to and including chrome/70.0:
   -> Intl.RelativeTimeFormat Intl.RelativeTimeFormat format should work for style narrow
      http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.RelativeTimeFormat
      locale data nu must be an object
   -> Intl.RelativeTimeFormat Intl.RelativeTimeFormat format should work for numeric auto
      http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.RelativeTimeFormat
      locale data nu must be an object
   -> Intl.RelativeTimeFormat Intl.RelativeTimeFormat formatToParts should work for numeric auto
      http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.RelativeTimeFormat
      locale data nu must be an object
```

**Comment by longlho** [comment]
Hmm is that from a clean build? The data format did change and it worked
locally for me after a clean install

**Comment by JakeChampion** [comment]
Yes, that was run on the last commit (https://github.com/Financial-Times/polyfill-library/pull/665/commits/1b1ae6e6e86814b63e1b3bffb55f595b3a060b45), CI always uses a clean build. You can view the build which failed -- https://github.com/Financial-Times/polyfill-library/runs/761250385

I can try rerunning the build if you want me to :-)

**Comment by longlho** [comment]
Nope that’s good enough let me debug on my side :) thanks!

**Comment by longlho** [comment]
I think I've fixed that issue :)

**Pull request merged**
