### PR TITLE
Extend support of IntersectionObserver for Opera Mini

### PR DESCRIPTION
**Pull request by matzimowski**
fixes https://github.com/Financial-Times/polyfill-library/issues/173

### CODE REVIEW

**Comment by JakeChampion** [comment]
Hi @matzimowski, have you tested whether the polyfill does infact work in those browsers?

**Comment by matzimowski** [comment]
Hi @JakeChampion 
I have used some emulator to check it (usage is described here: https://dev.opera.com/articles/installing-opera-mini-on-your-computer/)

you can see the user agent below:
Screenshot 2019-03-28 at 11 05 46

I've used IntersectionObserver in some SSR project and page was not working well:
Screenshot 2019-03-28 at 11 07 59

but when I changed from `features=IntersectionObserver,...` to `features=IntersectionObserver|always,...` it started working properly:

Screenshot 2019-03-28 at 11 12 05

**Comment by JakeChampion** [comment]
Emulators are perfectly good to use for testing this type of work, I use all the emulators on BrowserStack for testing :-)

Thanks for showing me that it does work, I feel confident accepting this change now 👍

**Comment by matzimowski** [comment]
@JakeChampion thank you!

**Pull request merged**
