### PR TITLE
chore: upgrade formatjs deps, fix #886

### LINKED ISSUE #886: Safari 14 Intl.NumberFormat usage throwing "Error: locale data nu must be an object"
# Bug Report

## What

Trying to initialize an `Intl.NumberFormat` object in Safari 14 with the latest version of the polyfill loaded throws an exception.

## Details

**Browser** 
Safari (Desktop) Version 14.0 (15610.1.28.1.9, 15610)

**Minimal code example**
https://jsbin.com/xikuwesiru/edit?html,console
```html
<script src="https://polyfill.io/v3/polyfill.min.js?features=Intl.~locale.ja" crossorigin></script>

<script>
  const nf = new Intl.NumberFormat();
  console.log(nf.format(1e3));
</script>
```

**Expected result**
Console logs: `1,000`
Screen Shot 2020-10-03 at 13 22 56

**Actual result**
`Error: locale data nu must be an object` is thrown.
Screen Shot 2020-10-03 at 13 23 31

**Possible workaround for users of pollyfill.io service**
Set the library to an earlier version without these polyfills: (i.e. https://polyfill.io/v3/polyfill.min.js?features=Intl.~locale.ja&version=3.89.4)

**More info**
* Saw it first time in the latest `polyfill-service` [release](https://github.com/Financial-Times/polyfill-service/releases/tag/v4.33.0)
* There's some indications this doesn't happen on Safari 13, but hard to validate.
* Safari 14 doesn't need this polyfill? (https://kangax.github.io/compat-table/esintl/#safari14)
* Seems gated vs non-gated doesn't make a difference.

### PR DESCRIPTION
**Pull request by longlho**

### CODE REVIEW

**Comment by JakeChampion** [comment]
@longlho it looks like something is wrong with the build, I'm guessing a babel helper is attempting to be used which is called `__assign`.

```
Failures:
 - ie 9/10/11:
    -> Intl.DateTimeFormat passes the feature detect
       Unable to get property '__assign' of undefined or null reference
    -> Intl.DateTimeFormat formatToParts should work
       Unable to get property '__assign' of undefined or null reference
    -> Intl.DateTimeFormat should fix dayperiod bug in chrome
       Unable to get property '__assign' of undefined or null reference
    http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.DateTimeFormat

    -> Intl.DisplayNames Intl.DisplayNames should be able to resolve Latin America
       Unable to get property '__assign' of undefined or null reference
    http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.DisplayNames
    
    -> Intl.ListFormat Intl.ListFormat format should work for style conjunction
       Unable to get property '__assign' of undefined or null reference
    http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.ListFormat
    
    -> Intl.NumberFormat passes the feature detect
       false == true
    -> Intl.NumberFormat format should work for compact notation
       Unable to get property '__assign' of undefined or null reference
    http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.NumberFormat
    
    -> Intl.PluralRules Intl.PluralRules should work for cardinal
       Unable to get property '__assign' of undefined or null reference
    http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.PluralRules
    
    -> Intl.PluralRules Intl.PluralRules should work for ordinal
       Unable to get property '__assign' of undefined or null reference
    -> Intl.RelativeTimeFormat Intl.RelativeTimeFormat format should work for style narrow
       Unable to get property '__assign' of undefined or null reference
    -> Intl.RelativeTimeFormat Intl.RelativeTimeFormat format should work for numeric auto
       Unable to get property '__assign' of undefined or null reference
    -> Intl.RelativeTimeFormat Intl.RelativeTimeFormat formatToParts should work for numeric auto
       Unable to get property '__assign' of undefined or null reference
    http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.RelativeTimeFormat
    
    -> Intl.getCanonicalLocales Intl.getCanonicalLocales should be able to resolve locale list
       Unable to get property '__assign' of undefined or null reference
    http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.getCanonicalLocales
```

**Comment by longlho** [comment]
ugh fun kk let me see

**Review by JakeChampion — CHANGES_REQUESTED** [review]
Currently failing the tests due to a missing function in the Intl bundles, when that is fixed this should hopefully pass all the tests and can be merged and released 👍

**Comment by longlho** [comment]
another try pls?

**Comment by JakeChampion** [comment]
@longlho its running on ci now :-)

**Comment by longlho** [comment]
all green!

**Review by JakeChampion — APPROVED** [review]
Thanks @longlho 🎉

**Pull request merged**
