### PR TITLE
feat: Add Intl.getCanonicalLocales polyfill

### PR DESCRIPTION
**Pull request by longlho**

### CODE REVIEW

**Comment by JakeChampion** [comment]
Hi @longlho thanks for the ping, I reran the tests on CI and it has shown a failure for iOS 10, do you think you would be able to look into that at all?

```
Failures:
 - ios/10:
    -> Intl.getCanonicalLocales Intl.getCanonicalLocales should be able to resolve locale list
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.getCanonicalLocales
       function is not a constructor (evaluating 'new Intl.getCanonicalLocales('en')')
```

**Comment by longlho** [comment]
@JakeChampion done :)

**Comment by JakeChampion** [comment]
@longlho, it looks like the test is not passing for iOS 10.

You can run the test server locally by running `npm install` and then running `node ./test/polyfills/server.js`. You can then visit `http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.getCanonicalLocales` in a web browser to have the test suite load and execute.

```
Failures:
 - ios/10:
    -> Intl.getCanonicalLocales Intl.getCanonicalLocales should be able to resolve locale list
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Intl.getCanonicalLocales
       function is not a constructor (evaluating 'new Intl.getCanonicalLocales('en')')
```

**Comment by longlho** [comment]
sry about that I forgot to commit the actual fix

**Comment by JakeChampion** [comment]
@longlho Excellent work here! Thank you so much for this :D

**Pull request merged**
